#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync vm-agent
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@$1
VM_AGENT_DIR=/opt/smartdc/agents/lib/node_modules/vm-agent

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
#else
#    # Clean node_modules everytime.
#    ssh $NODE rm -rf /zones/$SDC_ZONE/root/opt/smartdc/sdc/node_modules/imgapi-cli/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:${VM_AGENT_DIR} \
    $extraOpts \
    --exclude .git/ \
    --exclude /deps/ \
    --exclude /docs/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -H -o state vm-agent)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm clear vm-agent
else
    ssh ${NODE} svcadm restart vm-agent
fi
